### ISSUE TITLE
#Setup No Readme how to setup the backend properly

### ISSUE THREAD

**Issue by Dr4gon** [coyotiv-sose/graduation-project-marwerk#36]
@Marwerk Since I know the setup, I know I have to use Docker. A newbie would just use the scripts configured in package.json and run into this:

```
@Dr4gon ➜ /workspaces/review-marv/backend (main) $ npm run dev

> hotel-las-calas@0.0.0 dev
> nodemon ./bin/www

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node ./bin/www`
express-session deprecated req.secret; provide secret option src/app.js:45:27
Could not connect to MongoDB MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
/workspaces/review-marv/backend/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:206
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.createClient (/workspaces/review-marv/backend/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:206:11)
    at NativeConnection.openUri (/workspaces/review-marv/backend/node_modules/mongoose/lib/connection.js:738:34)
    at Mongoose.connect (/workspaces/review-marv/backend/node_modules/mongoose/lib/index.js:404:15)
    at Object.<anonymous> (/workspaces/review-marv/backend/src/database-connection.js:6:4)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)

Node.js v20.5.1
[nodemon] app crashed - waiting for file changes before starting...
```

Make sure that anyone new is able to at least start your app easily 😬

**Comment by Dr4gon** [comment]
Ok, even with Docker it's not yet running smoothly. I wouldn't know what an .env file is, if I'm a newbie. I create them manually to get the build running. I know they're on your ignore list to avoid uploading sensitive data. An idea: Build a script that automatically generates this on npm install or npm run dev.

```
@Dr4gon ➜ /workspaces/review-marv/backend (main) $ docker compose up backend
Failed to load /workspaces/review-marv/backend/.env: open /workspaces/review-marv/backend/.env: no such file or directory
@Dr4gon ➜ /workspaces/review-marv/backend (main) $ docker compose up backend
Failed to load /workspaces/review-marv/frontend/.env: open /workspaces/review-marv/frontend/.env: no such file or directory
@Dr4gon ➜ /workspaces/review-marv/backend (main) $ docker compose up backend
[+] Running 1/1
 ! backend Warning                                                         1.3s 
[+] Building 10.1s (7/11)              
```

**Comment by Dr4gon** [comment]
I updated .env with

```
VITE_API_BASE_URL=http://localhost:3000
```

and still run into this:

```
accountStore.js:19 We have an error while fetching user session: DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at dispatchXhrRequest (http://127.0.0.1:5173/node_modules/.vite/deps/axios.js?v=d35c9711:1399:13)
    at new Promise (<anonymous>)
    at xhr (http://127.0.0.1:5173/node_modules/.vite/deps/axios.js?v=d35c9711:1372:10)
    at Axios.dispatchRequest (http://127.0.0.1:5173/node_modules/.vite/deps/axios.js?v=d35c9711:1576:10)
    at Axios.request (http://127.0.0.1:5173/node_modules/.vite/deps/axios.js?v=d35c9711:1841:33)
    at Axios.<computed> [as get] (http://127.0.0.1:5173/node_modules/.vite/deps/axios.js?v=d35c9711:1860:17)
    at Function.wrap [as get] (http://127.0.0.1:5173/node_modules/.vite/deps/axios.js?v=d35c9711:6:15)
    at Proxy.fetchUser (http://127.0.0.1:5173/src/stores/accountStore.js:14:34)
    at Proxy.<anonymous> (http://127.0.0.1:5173/node_modules/.vite/deps/pinia.js?v=d35c9711:1100:22)
    at store.<computed> (http://127.0.0.1:5173/node_modules/.vite/deps/pinia.js?v=d35c9711:781:44)
```

Reproducer:

1. Open a codespace with the current code
2. Run npm i
3. Configure .env with VITE_API_BASE_URL=http://localhost:3000
4. docker compose up backend
5. npm run dev in frontend
6. Sign up as user
7. Try to login with successfully signed up user

**Comment by Dr4gon** [comment]
@Marwerk My bad there was an ASCII sign smuggled into the my configured URL. Now I get this while trying to sign up:
<img width="537" alt="Bildschirmfoto 2023-09-01 um 17 57 09" src="https://github.com/Marwerk/coyotiv-graduation-project/assets/4116724/07977237-ce11-4954-9f3b-254d6dc0e4fb">

It seems like the docker container doesn't have a working mongo environment running:

```
Fri, 01 Sep 2023 15:54:44 GMT express-session deprecated req.secret; provide secret option at src/app.js:45:27
review-marv-backend-1  | Could not connect to MongoDB MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
review-marv-backend-1  | /app/node_modules/mongoose/lib/connection.js:788
review-marv-backend-1  |     err = new ServerSelectionError();
review-marv-backend-1  |           ^
review-marv-backend-1  | 
review-marv-backend-1  | MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
review-marv-backend-1  |     at _handleConnectionErrors (/app/node_modules/mongoose/lib/connection.js:788:11)
review-marv-backend-1  |     at NativeConnection.asPromise (/app/node_modules/mongoose/lib/connection.js:1250:11) {
review-marv-backend-1  |   reason: TopologyDescription {
review-marv-backend-1  |     type: 'Unknown',
review-marv-backend-1  |     servers: Map(1) {
review-marv-backend-1  |       'mongo:27017' => ServerDescription {
review-marv-backend-1  |         address: 'mongo:27017',
review-marv-backend-1  |         type: 'Unknown',
review-marv-backend-1  |         hosts: [],
review-marv-backend-1  |         passives: [],
review-marv-backend-1  |         arbiters: [],
review-marv-backend-1  |         tags: {},
review-marv-backend-1  |         minWireVersion: 0,
review-marv-backend-1  |         maxWireVersion: 0,
review-marv-backend-1  |         roundTripTime: -1,
review-marv-backend-1  |         lastUpdateTime: 3082620,
review-marv-backend-1  |         lastWriteDate: 0,
review-marv-backend-1  |         error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
review-marv-backend-1  |             at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:367:20)
review-marv-backend-1  |             at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:290:22)
review-marv-backend-1  |             at Object.onceWrapper (node:events:629:26)
review-marv-backend-1  |             at Socket.emit (node:events:514:28)
review-marv-backend-1  |             at emitErrorNT (node:internal/streams/destroy:151:8)
review-marv-backend-1  |             at emitErrorCloseNT (node:internal/streams/destroy:116:3)
review-marv-backend-1  |             at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
review-marv-backend-1  |           cause: Error: getaddrinfo ENOTFOUND mongo
review-marv-backend-1  |               at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
review-marv-backend-1  |             errno: -3008,
review-marv-backend-1  |             code: 'ENOTFOUND',
review-marv-backend-1  |             syscall: 'getaddrinfo',
review-marv-backend-1  |             hostname: 'mongo'
review-marv-backend-1  |           },
review-marv-backend-1  |           [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
review-marv-backend-1  |         },
review-marv-backend-1  |         topologyVersion: null,
review-marv-backend-1  |         setName: null,
review-marv-backend-1  |         setVersion: null,
review-marv-backend-1  |         electionId: null,
review-marv-backend-1  |         logicalSessionTimeoutMinutes: null,
review-marv-backend-1  |         primary: null,
review-marv-backend-1  |         me: null,
review-marv-backend-1  |         '$clusterTime': null
review-marv-backend-1  |       }
review-marv-backend-1  |     },
review-marv-backend-1  |     stale: false,
review-marv-backend-1  |     compatible: true,
review-marv-backend-1  |     heartbeatFrequencyMS: 10000,
review-marv-backend-1  |     localThresholdMS: 15,
review-marv-backend-1  |     setName: null,
review-marv-backend-1  |     maxElectionId: null,
review-marv-backend-1  |     maxSetVersion: null,
review-marv-backend-1  |     commonWireVersion: 0,
review-marv-backend-1  |     logicalSessionTimeoutMinutes: null
review-marv-backend-1  |   },
review-marv-backend-1  |   code: undefined
review-marv-backend-1  | }
```
